### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by RonakR** [jakemmarsh/react-rocket-boilerplate#2]
Hey there,

I tried setting up this project so I could reverse engineer it and see how React works. 
But, it looks like I'm already having problems. 
I followed all the instructions on the readme (i.e. npm installl, gulp dev) but Chrome is telling me 'React is not defined). 
So I went ahead and added 'var React         = require('react/addons');' to CurrentUsersActions.js and Routes.js which seemed to fix that problem. 
But then I got the 'No 'Access-Control-Allow-Origin' header is present on the requested resource.' 

I have no idea how to fix that and I was wondering if you could guide me on that one. 

Thanks.

**Comment by jakemmarsh** [comment]
Good catch on the React require. It should only be necessary in `Routes.js`, and I just updated this in 089db66.

As for the `No 'Access-Control-Allow-Origin'`, I think you're referring to when it's attempting to access `localhost:3000/api/check`. This is due to [`App.js` calling `UserActions.checkLoginStatus`](https://github.com/jakemmarsh/react-rocket-boilerplate/blob/master/app/js/App.js#L38), which makes an API call [inside the CurrentUserStore](https://github.com/jakemmarsh/react-rocket-boilerplate/blob/master/app/js/App.js#L38). This API call is carried out in APIUtils, where a [root domain for your API should be defined](https://github.com/jakemmarsh/react-rocket-boilerplate/blob/master/app/js/utils/APIUtils.js#L10). It defaults to `//localhost:3000`, which is causing the error you mentioned. 

You can either fix this root domain to point to a real API (you may also want to change the URL specified in [`AuthAPI`](https://github.com/jakemmarsh/react-rocket-boilerplate/blob/master/app/js/utils/AuthAPI.js#L8`), or you can remove the `CurrentUser` logic and `checkLoginStatus` call.

**Comment by RonakR** [comment]
Yes, that is what I was referring to. I tried removing the CurrentUser logic but that turned out to be a bigger rabbit hole than I guessed.
Did some research and now looking into the CORS (http://stackoverflow.com/questions/24671032/cross-domain-ajax-call-to-localhost-web-api).

**Comment by jakemmarsh** [comment]
This isn't an issue with CORS. If you were actually sending an HTTP request to a real API, that could be the problem. But the issue here is that (I'm assuming) you don't actually have an API server running locally and so the URL `localhost:3000/api/check` does not exist.

To completely remove the CurrentUser logic:
1. remove lines `7`, `10`, `11`, `17`, `19-31`, `37-40`, and `50` (make sure to maintain the JSX format when removing this line). This will eliminate any API calls, and fix your problem.
2. (optional) if you don't plan on replacing the logic later, you can remove the files:
    - `/stores/CurrentUserStore.js` 
    - `/actions/CurrentUserActions.js`
    - `/mixins/AuthenticatedRouteMixin.js`

**Comment by RonakR** [comment]
Yes, I do not have an API server running locally. 

But, your suggested changes seemed to do the trick. 
Thanks!
