### ISSUE TITLE
what does the polling exactly mean after start with "gulp dev"

### ISSUE THREAD

**Issue by vikbert** [jakemmarsh/react-rocket-boilerplate#3]
after start the application with `gulp dev`, the terminal shows the continual polling requests:

```
GET /socket.io/?EIO=3&transport=polling&t=1428085298729-39813 200 0.927 ms - 431
GET /socket.io/?EIO=3&transport=polling&t=1428085298737-39814 200 0.877 ms - 431
GET /socket.io/?EIO=3&transport=polling&t=1428085298746-39815 200 0.851 ms - 431
GET /socket.io/?EIO=3&transport=polling&t=1428085298755-39816 200 0.904 ms - 431
GET /socket.io/?EIO=3&transport=polling&t=1428085298763-39817 200 0.855 ms - 431
GET /socket.io/?EIO=3&transport=polling&t=1428085298771-39818 200 0.899 ms - 431
GET /socket.io/?EIO=3&transport=polling&t=1428085298779-39819 200 1.091 ms - 431
GET /socket.io/?EIO=3&transport=polling&t=1428085298788-39820 200 0.892 ms - 431
GET /socket.io/?EIO=3&transport=polling&t=1428085298805-39821 200 0.853 ms - 431
GET /socket.io/?EIO=3&transport=polling&t=1428085298814-39822 200 0.991 ms - 431
GET /socket.io/?EIO=3&transport=polling&t=1428085298822-39823 200 0.848 ms - 431
```

what does exactly mean? Can I disable the output in termina?

**Comment by jakemmarsh** [comment]
This is output from browser-sync, which works through WebSockets. I'm not sure why, but a recent change/update made it spam the Express server (I've noticed this problem as well). It can be fixed by removing [line 15 of server.js](https://github.com/jakemmarsh/react-rocket-boilerplate/blob/master/gulp/tasks/server.js#L15).

That `morgan('dev')` line makes the Express server log all requests. It can be useful, but when browser-sync spams it it quickly becomes annoying. I'm not sure if this should this be fully removed?

**Comment by keonkim** [comment]
I had same issue when I had two clients open.

**Comment by jakemmarsh** [comment]
This should no longer be an issue now that I've removed the Express server and switched over to solely browser-sync in 7ced1ac3ee127cfa9c1285222e6195cde3438845
