### ISSUE TITLE
XMLHttpRequest cannot load, Revisited

### ISSUE THREAD

**Issue by tiagoj** [jakemmarsh/react-rocket-boilerplate#8]
Here is a possible fix for the issue:

When the page first loads, grab the page url, then set that base url into APIUtils.root, so then it can use whatever port any proxy has changed it to.

Code:  
(add to App.js imports)

import APIUtils           from './utils/APIUtils';

(add to App.js, in componentWillMount() )

    // To support proxy by Browsersync on different port,
    // set api utils to use same root url as original page
    var url = window.location.href;
    var tmpAnchor = document.createElement('a');
    tmpAnchor.href = url;
    var rootUrl = tmpAnchor.protocol+"//"+tmpAnchor.hostname+":"+tmpAnchor.port;
    APIUtils.root = rootUrl+"/api/"

This seems to work, although I did not test very much.

**Comment by jakemmarsh** [comment]
All you're doing here is essentially changing `APIUtils.root` to the current URL.

The XMLHttpRequest error is really not a bug, the API logic is merely a placeholder as an example of how you could interact with your API. It throws the error because it's attempting to access an API where one is not being run, thus throwing the cross-origin error.

If you're not trying to interact with your own (or any API), instead of dynamically changing `APIUtils.root` you can just remove all of this boilerplate code. I give step-by-step directions [here](https://github.com/jakemmarsh/react-rocket-boilerplate/issues/2)
